spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxx
    password: xxx
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
kafka:
  bootstrapAddress: localhost:9092
  groupId: mail_service
  topics:
    email: template_email_sender
